index:
    path: /
    controller: App\Controller\DefaultController::index

test:
    path: /test
    controller: App\Controller\DefaultController::test

anketCreate:
        path: /anket/create
        controller: App\Controller\AnketController::create

anketStore:
                path: /anket/store
                controller: App\Controller\AnketController::store

anketList:
     path: /anket
     controller: App\Controller\AnketController::list